#!/bin/bash

scriptname="$(basename $0)"
filename=$1
name=$(echo "$filename" | cut -f 1 -d '.')

if [[ -z "$filename" ]]; then
  echo "USAGE: $scriptname {filename}.cpp"
  exit
fi

if ! g++ "$filename" -o "$name"; then
  exit 1
fi

./"$name"

rm $name
